### ISSUE TITLE
Exception on second render of template when `app_namespace.Loader` is not first.

### ISSUE THREAD

**Issue by mrmachine** [Fantomas42/django-app-namespace-template-loader#16]
With:

```python
TEMPLATES_DJANGO = {
    ...
    'OPTIONS': {
        ...
        'loaders': [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
            'app_namespace.Loader',
        ],
    },
}
```

I get the following on second and subsequent request for a page that is extended with a namespace:

```
Traceback (most recent call last):
  File "/Users/tailee/.pyenv/versions/2.7.10/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 383, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 313, in get_traceback_data
    } for t in source_list_func(str(self.exc_value))]
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 270, in format_path_status
    if not os.path.exists(path):
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NamespaceOrigin found
```

This shows up in stdout for `manage.py runserver` and the browser just says `A server error occurred.  Please contact the administrator.` even thought `DEBUG` is `True`.

I assume this error is because on the first request, the template is found by `app_namespace.Loader` which creates a `NamespaceOrigin` which is somehow cached across requests. On second request, the `NamespaceOrigin` is being passed to Django's loaders which expect a simple string.

If it is required that `app_namespace.Loader` be first, this should be documented. Although it seems like this should not be a requirement. Perhaps `NamespaceOrigin` objects need a `__unicode__()` method or something, so they can be passed to other loaders, even if the unicode value is something that will never match another loader. Or perhaps the `NamespaceOrigin` object shouldn't be cached across requests?

**Comment by Fantomas42** [comment]
With tests i have reproduced and fixed the issue.

Regards

**Comment by Fantomas42** [comment]
Hum it's seem to not work with Django 1.8... I will provide a new fix.

**Comment by Fantomas42** [comment]
A new release available on PyPI has been uploaded.

**Comment by mrmachine** [comment]
Thanks very much for quickly fixing these issues and publishing a new release on PyPI. Odd that it's only Django 1.8 that needs the loader to be first? Is that not the case on both 1.7 and 1.9?

**Comment by Fantomas42** [comment]
In 1.9 the loader position is not important, I have tested it.

For the previous version I think it was mandatory but not a known issue...
For the future, it's now fixed.

Internal and undocumented changes within Django, are a mess.
