### ISSUE TITLE
Unexpected behaviour when using an invalid namespace.

### ISSUE THREAD

**Issue by mrmachine** [Fantomas42/django-app-namespace-template-loader#17]
I had a template `icekit/integration/reversion/templates/admin/fluent_pages/page/change_list.html` that had `{% extends "icekit:admin/fluent_pages/page/change_list.html" %}` at the top and which defined `{% block object-tools-items %}` to add a "Recover deleted pages" button.

At some point, the `icekit/templates/admin/fluent_pages/page/change_list.html` file was removed, because its overrides were no longer needed.

Surprisingly, the pages change list still rendered the reversion integration template, but it **duplicated** the contents of the `object-tools-items` block, so there were **two** "Recover deleted pages" buttons.

I tried `{% extends "icekit:admin/fluent_pages/page/change_list.html" %}` and even `{% extends "foo:admin/fluent_pages/page/change_list.html" %}` (`foo` being an invalid app namespace) and `{% extends "admin:admin/fluent_pages/page/change_list.html" %}` (`admin` being a valid app namespace, but not one that contained the specified template). All these exhibited the same behaviour.

Only specifying a different valid app namespace (where the template exists) worked: `{% extends "fluent_pages:admin/fluent_pages/page/change_list.html" %}`.

I would expect an invalid app namespace to either raise an exception (if `DEBUG=True`) or fail to match any templates. I would expect a valid namespace that doesn't contain the specified template to fail to match. I would expect an empty namespace to match the first app namespace that contains the template according to `INSTALLED_APPS` order.

**Comment by Fantomas42** [comment]
> I would expect an invalid app namespace to either raise an exception (if DEBUG=True) or fail to match any templates. I would expect a valid namespace that doesn't contain the specified template to fail to match. I would expect an empty namespace to match the first app namespace that contains the template according to INSTALLED_APPS order.

This behavior is now fixed. 
Thanks for your report.

**Comment by mrmachine** [comment]
Thanks for the quick update. This fix also seems to expose another edge case that breaks like #16 -- After making this change, when I specify an invalid app namespace in my `{% extends %}` tag, I get:

```
Traceback (most recent call last):
  File "/Users/tailee/.pyenv/versions/2.7.10/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 383, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 313, in get_traceback_data
    } for t in source_list_func(str(self.exc_value))]
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/site-packages/django/views/debug.py", line 270, in format_path_status
    if not os.path.exists(path):
  File "/Users/tailee/.virtualenvs/icekit-sprint/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NamespaceOrigin found
```

**Comment by Fantomas42** [comment]
Which version of Django do you use ?

**Comment by mrmachine** [comment]
1.8
